// ---------------------------------------------------------------------------
// Image upload — shared by the avatar and event-cover-image endpoints.
//
// Files are held in memory just long enough to be sniffed, then stored as a
// row in the `images` table under an id generated by the database, never the
// client's filename. The client's filename and declared Content-Type are only
// used for an early, cheap rejection — both are trivial to fake, so the real
// gate is the magic-byte check in saveUploadedImage(), which looks at the
// actual bytes before anything is stored.
//
// Why the database and not the disk: Render's free tier has an ephemeral
// filesystem, so anything written to disk disappeared on every redeploy and
// every idle spin-down. A 5MB-capped image in Postgres survives both, costs
// nothing extra, and needs no third-party storage account.
//
// This is a type/size gate only, not content moderation — screening what's
// actually IN the image would mean a third-party API, which is out of scope
// here.
// ---------------------------------------------------------------------------

import path from "node:path";
import multer from "multer";
import prisma from "../db/prisma.js";
import { isUuid } from "./validateEvent.js";

const ALLOWED_MIME_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);
const MAX_FILE_BYTES = 5 * 1024 * 1024;

// Magic-byte signatures for the three formats accepted. Checked against the
// actual file bytes in saveUploadedImage(), after multer's fileFilter has
// already done the cheap Content-Type check. A client can set
// "Content-Type: image/png" on an .exe as easily as it can rename the file,
// so the header bytes are the only thing worth trusting.
const SIGNATURES = [
  { mime: "image/jpeg", ext: "jpg", bytes: [0xff, 0xd8, 0xff] },
  { mime: "image/png", ext: "png", bytes: [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a] },
  // WEBP is a RIFF container: bytes 0-3 are "RIFF", bytes 8-11 are "WEBP".
  { mime: "image/webp", ext: "webp", bytes: [0x52, 0x49, 0x46, 0x46], riff: true }
];

function sniffImageType(buffer) {
  for (const sig of SIGNATURES) {
    if (buffer.length < sig.bytes.length) continue;
    if (!sig.bytes.every((b, i) => buffer[i] === b)) continue;
    if (sig.riff && buffer.subarray(8, 12).toString("ascii") !== "WEBP") continue;
    return { mime: sig.mime, ext: sig.ext };
  }
  return null;
}

/** Marks an Error as a client-caused upload problem, not a server failure. */
function uploadError(message) {
  const err = new Error(message);
  err.isUploadValidation = true;
  return err;
}

function fileFilter(_req, file, cb) {
  if (!ALLOWED_MIME_TYPES.has(file.mimetype)) {
    return cb(uploadError(
      `Unsupported file type: ${file.mimetype}. Only JPEG, PNG, and WEBP images are allowed.`
    ));
  }
  cb(null, true);
}

/** multer middleware — mount as `imageUpload.single("<fieldName>")`. */
export const imageUpload = multer({
  storage: multer.memoryStorage(),
  fileFilter,
  limits: { fileSize: MAX_FILE_BYTES, files: 1 }
});

/**
 * Verify the uploaded buffer really is one of the allowed image types (by
 * content, not by the Content-Type header fileFilter already checked) and
 * store it. Returns the stored filename: "<uuid>.<ext>", where the extension
 * comes from the sniffed type — never from the client's filename.
 *
 * Throws an Error with `.isUploadValidation = true` on a bad file — callers
 * turn that into this codebase's normal { message, errors } envelope, the
 * same as any other validation failure.
 */
export async function saveUploadedImage(file) {
  if (!file?.buffer?.length) {
    throw uploadError("Uploaded file was empty.");
  }

  const detected = sniffImageType(file.buffer);
  if (!detected) {
    throw uploadError("That file doesn't look like a JPEG, PNG, or WEBP image.");
  }

  const image = await prisma.storedImage.create({
    data: { mimeType: detected.mime, data: file.buffer, byteSize: file.buffer.length },
    select: { id: true }
  });

  return `${image.id}.${detected.ext}`;
}

/** The public path an image is served from, given its stored filename. */
export const publicUploadUrl = (filename) => `/uploads/${filename}`;

/**
 * Pull the image id out of a stored filename or a "/uploads/<id>.<ext>" URL.
 * Anything that isn't exactly a UUID — an external URL like a seeded avatar,
 * or a path with "../" in it — yields null, so it can never be looked up.
 */
export function imageIdFromUrl(urlOrFilename) {
  if (!urlOrFilename) return null;
  const id = path.basename(String(urlOrFilename)).replace(/\.(jpg|png|webp)$/i, "");
  return isUuid(id) ? id : null;
}

/**
 * Best-effort delete of a previously uploaded image. Never throws: a stale
 * row left behind costs a little space, not correctness, so cleanup failing
 * shouldn't fail the request that triggered it.
 */
export async function deleteUploadedImage(urlOrFilename) {
  const id = imageIdFromUrl(urlOrFilename);
  if (!id) return;
  await prisma.storedImage.delete({ where: { id } }).catch(() => {});
}

/**
 * GET /uploads/:filename — serve a stored image.
 *
 * Image ids are never reused (a replaced avatar gets a new id), so the
 * response can be cached forever by the browser and any CDN in front.
 */
export async function serveUploadedImage(req, res, next) {
  const id = imageIdFromUrl(req.params.filename);
  if (!id) return res.status(404).json({ message: "Image not found" });

  try {
    const image = await prisma.storedImage.findUnique({
      where: { id },
      select: { mimeType: true, data: true }
    });
    if (!image) return res.status(404).json({ message: "Image not found" });

    res.set({
      "Content-Type": image.mimeType,
      "Cache-Control": "public, max-age=31536000, immutable",
      "X-Content-Type-Options": "nosniff"
    });
    res.send(Buffer.from(image.data));
  } catch (error) {
    next(error);
  }
}
